################################# Default configuration ###################
# provide your domain here
baseURL = "https://ibisba.github.io/handbook/"
# theme
theme = "dot"
# site title
title = "IBISBA"
# desable language
disableLanguages = []
publishDir = "docs"
############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#8cbb2d"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://formspree.io/meqreyqe" # contact form works with : https://formspree.io

############################## social links ##############################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#  
#[[params.social]]
#icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#  
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"


################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Access"
  url = "access"
  weight = 1
  [[menu.main]]
  parent = "docs"
  name = "Project management"
  url = "project_management"
  weight = 2
  [[menu.main]]
  parent = "docs"
  name = "IBISBA Hub"
  url = "ibisba_hub"
  weight = 3
  [[menu.main]]
  parent = "docs"
  name = "Protocols"
  url = "protocols"
  weight = 4
  [[menu.main]]
  parent = "docs"
  name = "Standardisation"
  url = "standardisation"
  weight = 5
  [[menu.main]]
  parent = "docs"
  name = "Handbook"
  url = "handbook"
  weight = 6
  [[menu.main]]
  parent = "docs"
  name = "FAQ"
  url = "faq"
  weight = 7

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "IBISBA handbook base"
description = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# Github
[Languages.en.params.github]
title = "Edit on GitHub"
description = "Edit this page on GitHub"
git_image = "images/GitHub-Mark-32px.png"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Leave a message and we will get back to you shortly"
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"

[frontmatter]
lastmod = ["lastmod", ":fileModDate", "date"]
