name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: ibisba.github.io/handbook
          destination_token: ${{ secrets.PERSONAL_TOKEN }}
